[package]
name = "experiences_types"
version = "0.1.0"
edition = "2021"


[lib]
name = "experiences_types_lib"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.208", features = ["derive"] }

[features]
client = []